# Generated by Django 5.2.12 on 2026-07-04 02:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Evento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('simples', 'Evento simples'), ('inscricao', 'Evento com inscrição')], default='simples', max_length=20, verbose_name='Tipo do evento')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do evento')),
                ('local', models.CharField(blank=True, max_length=200, verbose_name='Local do evento')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição do evento')),
                ('data', models.DateField(verbose_name='Data do evento')),
                ('horario_inicio', models.TimeField(blank=True, null=True, verbose_name='Horário de início')),
                ('horario_fim', models.TimeField(blank=True, null=True, verbose_name='Horário de término')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Evento',
                'verbose_name_plural': 'Eventos',
                'ordering': ['-data', '-horario_inicio'],
            },
        ),
    ]
