# Generated by Django 5.2.12 on 2026-07-04 02:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='data_fim',
            field=models.DateField(blank=True, null=True, verbose_name='Data de término'),
        ),
        migrations.CreateModel(
            name='CustoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Título do custo')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='eventos/custos/', verbose_name='Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_evento_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='custos', to='core.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Custo do evento',
                'verbose_name_plural': 'Custos do evento',
                'ordering': ['-criado_em'],
            },
        ),
    ]
