# Generated by Django 5.2.12 on 2026-07-04 13:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_evento_data_fim_custoevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricao_aberta_publico',
            field=models.BooleanField(default=False, verbose_name='Aberto ao público geral'),
        ),
        migrations.AddField(
            model_name='evento',
            name='inscricao_limite',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo limite de inscrição'),
        ),
        migrations.AddField(
            model_name='evento',
            name='valor_diretoria',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor para a diretoria'),
        ),
        migrations.CreateModel(
            name='FaixaEtariaPreco',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(blank=True, help_text='Opcional. Ex.: "Crianças". Se vazio, mostra a faixa de idades.', max_length=60, verbose_name='Rótulo da faixa')),
                ('idade_min', models.PositiveIntegerField(default=0, verbose_name='Idade mínima')),
                ('idade_max', models.PositiveIntegerField(default=0, verbose_name='Idade máxima')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='faixas_preco', to='core.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Faixa etária (preço)',
                'verbose_name_plural': 'Faixas etárias (preços)',
                'ordering': ['ordem', 'idade_min', 'id'],
            },
        ),
    ]
