# Generated by Django 5.2.12 on 2026-07-04 13:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0004_evento_inscricao_aberta_publico_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CampoInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rotulo', models.CharField(max_length=150, verbose_name='Pergunta / rótulo')),
                ('tipo', models.CharField(choices=[('texto', 'Texto curto'), ('texto_longo', 'Texto longo'), ('numero', 'Número'), ('escolha_unica', 'Escolha única'), ('escolha_multipla', 'Escolha múltipla'), ('sim_nao', 'Sim/Não'), ('data', 'Data')], default='texto', max_length=20, verbose_name='Tipo do campo')),
                ('opcoes', models.TextField(blank=True, help_text='Uma opção por linha (só para escolha única/múltipla).', verbose_name='Opções')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Obrigatório')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='campos_inscricao', to='core.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Campo de inscrição',
                'verbose_name_plural': 'Campos de inscrição',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
