# Generated by Django 5.2.12 on 2026-07-04 13:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0005_campoinscricao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('responsavel_nome', models.CharField(max_length=150, verbose_name='Nome do responsável')),
                ('responsavel_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('responsavel_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('responsavel_cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da inscrição')),
                ('status', models.CharField(choices=[('confirmada', 'Confirmada'), ('cancelada', 'Cancelada')], default='confirmada', max_length=12, verbose_name='Situação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inscricoes', to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (se logado)')),
            ],
            options={
                'verbose_name': 'Inscrição',
                'verbose_name_plural': 'Inscrições',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParticipanteInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do participante')),
                ('idade', models.PositiveIntegerField(blank=True, null=True, verbose_name='Idade')),
                ('eh_diretoria', models.BooleanField(default=False, verbose_name='É da diretoria')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('faixa', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='participantes', to='core.faixaetariapreco', verbose_name='Faixa aplicada')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='participantes', to='core.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Participante da inscrição',
                'verbose_name_plural': 'Participantes da inscrição',
                'ordering': ['id'],
            },
        ),
        migrations.CreateModel(
            name='RespostaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('campo_rotulo', models.CharField(blank=True, max_length=150, verbose_name='Pergunta')),
                ('valor', models.TextField(blank=True, verbose_name='Resposta')),
                ('campo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='respostas', to='core.campoinscricao', verbose_name='Campo')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.inscricao', verbose_name='Inscrição')),
            ],
            options={
                'verbose_name': 'Resposta da inscrição',
                'verbose_name_plural': 'Respostas da inscrição',
                'ordering': ['id'],
            },
        ),
    ]
