# Generated by Django 5.2.12 on 2026-07-04 14:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_inscricao_participanteinscricao_respostainscricao'),
    ]

    operations = [
        migrations.AddField(
            model_name='campoinscricao',
            name='por_participante',
            field=models.BooleanField(default=False, verbose_name='Perguntar para cada participante'),
        ),
        migrations.AddField(
            model_name='respostainscricao',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='respostas', to='core.participanteinscricao', verbose_name='Participante'),
        ),
    ]
