# Generated by Django 5.2.12 on 2026-07-04 14:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_campoinscricao_por_participante_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='eventos/produtos/', verbose_name='Foto')),
                ('controla_estoque', models.BooleanField(default=False, verbose_name='Controlar estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='À venda')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='produtos', to='core.evento', verbose_name='Evento')),
            ],
            options={
                'verbose_name': 'Produto da lojinha',
                'verbose_name_plural': 'Produtos da lojinha',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariacaoProduto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=80, verbose_name='Nome da variação')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='core.produtoevento', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Variação de produto',
                'verbose_name_plural': 'Variações de produto',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
