# Generated by Django 5.2.12 on 2026-07-04 15:10

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_produtoevento_variacaoproduto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PedidoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nome', models.CharField(max_length=150, verbose_name='Nome do comprador')),
                ('comprador_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('comprador_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código do pedido')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=12, verbose_name='Situação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='pedidos', to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_loja', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (se logado)')),
            ],
            options={
                'verbose_name': 'Pedido da lojinha',
                'verbose_name_plural': 'Pedidos da lojinha',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ItemPedidoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=150, verbose_name='Produto')),
                ('variacao_nome', models.CharField(blank=True, max_length=80, verbose_name='Variação')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_pedido', to='core.variacaoproduto', verbose_name='Variação')),
                ('pedido', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.pedidoloja', verbose_name='Pedido')),
            ],
            options={
                'verbose_name': 'Item do pedido',
                'verbose_name_plural': 'Itens do pedido',
                'ordering': ['id'],
            },
        ),
    ]
