# Generated by Django 5.2.12 on 2026-07-04 16:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0009_pedidoloja_itempedidoloja'),
    ]

    operations = [
        migrations.AddField(
            model_name='pedidoloja',
            name='inscricao',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos', to='core.inscricao', verbose_name='Inscrição vinculada'),
        ),
    ]
