# Generated by Django 5.2.12 on 2026-07-04 17:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0011_pedidoloja_forma_pagamento_pedidoloja_origem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='inscricao',
            name='forma_pagamento',
            field=models.CharField(choices=[('online', 'Online (site)'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('cortesia', 'Cortesia')], default='online', max_length=12, verbose_name='Forma de pagamento'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='origem',
            field=models.CharField(choices=[('online', 'Online'), ('pdv', 'PDV (balcão)')], default='online', max_length=10, verbose_name='Origem'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='registrado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='valor_recebido',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor recebido'),
        ),
    ]
