# Generated by Django 5.2.12 on 2026-07-04 19:37

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0012_inscricao_forma_pagamento_inscricao_origem_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PerfilUsuario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('precisa_trocar_senha', models.BooleanField(default=False, verbose_name='Precisa trocar a senha no próximo login')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='perfil', to=settings.AUTH_USER_MODEL, verbose_name='Usuário')),
            ],
        ),
        migrations.CreateModel(
            name='OperadorEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('externo', models.BooleanField(default=False, verbose_name='Ajudante externo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operadores', to='core.evento', verbose_name='Evento')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='eventos_operados', to=settings.AUTH_USER_MODEL, verbose_name='Operador')),
            ],
            options={
                'verbose_name': 'Operador do evento',
                'verbose_name_plural': 'Operadores do evento',
                'ordering': ['evento', 'usuario__username'],
                'unique_together': {('evento', 'usuario')},
            },
        ),
    ]
