# Generated by Django 5.2.12 on 2026-07-05 00:15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0013_perfilusuario_operadorevento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CupomDesconto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código')),
                ('percentual', models.PositiveIntegerField(verbose_name='Percentual de desconto (%)')),
                ('ativo', models.BooleanField(default=True, verbose_name='Ativo')),
                ('usado_por', models.CharField(blank=True, max_length=150, verbose_name='Usado por')),
                ('valor_desconto', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor descontado')),
                ('usado_em', models.DateTimeField(blank=True, null=True, verbose_name='Usado em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cupons', to='core.evento', verbose_name='Evento')),
                ('inscricao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons', to='core.inscricao', verbose_name='Inscrição que usou')),
            ],
            options={
                'verbose_name': 'Cupom de desconto',
                'verbose_name_plural': 'Cupons de desconto',
                'ordering': ['-criado_em'],
            },
        ),
    ]
