# Generated by Django 5.2.12 on 2026-07-05 00:42

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0014_cupomdesconto'),
    ]

    operations = [
        migrations.AddField(
            model_name='cupomdesconto',
            name='faixa',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons', to='core.faixaetariapreco', verbose_name='Faixa etária do cupom'),
        ),
        migrations.AddField(
            model_name='cupomdesconto',
            name='participante',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cupons', to='core.participanteinscricao', verbose_name='Participante que usou'),
        ),
    ]
