# Generated by Django 5.2.12 on 2026-07-05 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_cupomdesconto_faixa_cupomdesconto_participante'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='itempedidoloja',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última entrega em'),
        ),
        migrations.AddField(
            model_name='itempedidoloja',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_entregues', to=settings.AUTH_USER_MODEL, verbose_name='Entrega registrada por'),
        ),
        migrations.AddField(
            model_name='itempedidoloja',
            name='quantidade_entregue',
            field=models.PositiveIntegerField(default=0, verbose_name='Quantidade entregue'),
        ),
        migrations.AddField(
            model_name='participanteinscricao',
            name='presente',
            field=models.BooleanField(default=False, verbose_name='Presente (check-in)'),
        ),
        migrations.AddField(
            model_name='participanteinscricao',
            name='presente_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Check-in em'),
        ),
        migrations.AddField(
            model_name='participanteinscricao',
            name='presente_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='checkins_registrados', to=settings.AUTH_USER_MODEL, verbose_name='Check-in registrado por'),
        ),
    ]
