# Generated by Django 5.2.12 on 2026-07-05 19:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_itempedidoloja_entregue_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PresencaEvento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('marcado_em', models.DateTimeField(auto_now_add=True, verbose_name='Marcado em')),
                ('aventureiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.aventureiro', verbose_name='Aventureiro')),
                ('evento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='presencas', to='core.evento', verbose_name='Evento')),
                ('marcado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='presencas_marcadas', to=settings.AUTH_USER_MODEL, verbose_name='Marcado por')),
            ],
            options={
                'verbose_name': 'Presença',
                'verbose_name_plural': 'Presenças',
                'ordering': ['-marcado_em'],
                'unique_together': {('evento', 'aventureiro')},
            },
        ),
    ]
