# Generated by Django 5.2.12 on 2026-07-05 20:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0017_presencaevento'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventureiro',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Ativo (frequenta o clube)'),
        ),
    ]
