# Generated by Django 5.2.12 on 2026-07-05 20:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0018_aventureiro_ativo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_id', models.CharField(blank=True, max_length=150, verbose_name='ID da instância')),
                ('token', models.CharField(blank=True, max_length=255, verbose_name='Token da instância')),
                ('base_url', models.CharField(blank=True, default='https://api.w-api.app/v1', max_length=200, verbose_name='URL base da API')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='whatsapp_configs', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração do WhatsApp',
                'verbose_name_plural': 'Configuração do WhatsApp',
            },
        ),
    ]
