# Generated by Django 5.2.12 on 2026-07-05 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0019_whatsappconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='whatsapp_principal_origem',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('resp', 'Responsável legal')], max_length=4, verbose_name='WhatsApp principal (origem)'),
        ),
    ]
