# Generated by Django 5.2.12 on 2026-07-05 23:48

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0020_perfilusuario_whatsapp_principal_origem'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome do produto')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('foto', models.ImageField(blank=True, null=True, upload_to='loja/produtos/', verbose_name='Foto')),
                ('composto', models.BooleanField(default=False, verbose_name='Produto composto (com grupos)')),
                ('controla_estoque', models.BooleanField(default=False, verbose_name='Controlar estoque')),
                ('ativo', models.BooleanField(default=True, verbose_name='À venda')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Produto da loja',
                'verbose_name_plural': 'Produtos da loja',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='CompraLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comprador_nome', models.CharField(max_length=150, verbose_name='Nome do comprador')),
                ('comprador_whatsapp', models.CharField(blank=True, max_length=20, verbose_name='WhatsApp')),
                ('comprador_email', models.EmailField(blank=True, max_length=254, verbose_name='E-mail')),
                ('codigo', models.CharField(max_length=20, unique=True, verbose_name='Código da compra')),
                ('status', models.CharField(choices=[('confirmado', 'Confirmado'), ('cancelado', 'Cancelado')], default='confirmado', max_length=12, verbose_name='Situação')),
                ('forma_pagamento', models.CharField(choices=[('online', 'Online (site)'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('cortesia', 'Cortesia')], default='online', max_length=12, verbose_name='Forma de pagamento')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_loja', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (comprador)')),
            ],
            options={
                'verbose_name': 'Compra da loja',
                'verbose_name_plural': 'Compras da loja',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='GrupoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome do grupo')),
                ('modo', models.CharField(choices=[('unica', 'Escolha única (1 opção da lista)'), ('itens', 'Itens (vários, cada um com quantidade)')], default='itens', max_length=10, verbose_name='Modo')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Grupo obrigatório')),
                ('orientacao', models.TextField(blank=True, verbose_name='Orientação')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='grupos', to='core.produtoloja', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Grupo de variações',
                'verbose_name_plural': 'Grupos de variações',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='VariacaoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, max_length=100, verbose_name='Nome da variação')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Preço')),
                ('estoque', models.PositiveIntegerField(default=0, verbose_name='Estoque')),
                ('obrigatorio', models.BooleanField(default=False, verbose_name='Item obrigatório')),
                ('ativo', models.BooleanField(default=True, verbose_name='Disponível')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('grupo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='variacoes', to='core.grupoloja', verbose_name='Grupo')),
            ],
            options={
                'verbose_name': 'Variação da loja',
                'verbose_name_plural': 'Variações da loja',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='ItemCompraLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('produto_nome', models.CharField(max_length=150, verbose_name='Produto')),
                ('grupo_nome', models.CharField(blank=True, max_length=100, verbose_name='Grupo')),
                ('variacao_nome', models.CharField(blank=True, max_length=100, verbose_name='Variação')),
                ('aventureiro_nome', models.CharField(blank=True, max_length=150, verbose_name='Aventureiro')),
                ('quantidade', models.PositiveIntegerField(default=1, verbose_name='Quantidade')),
                ('valor_unitario', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor unitário')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('kit', models.PositiveIntegerField(default=0, verbose_name='Kit')),
                ('aventureiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_loja', to='core.aventureiro', verbose_name='Aventureiro (para quem é)')),
                ('compra', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='itens', to='core.compraloja', verbose_name='Compra')),
                ('produto', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_comprados', to='core.produtoloja', verbose_name='Produto')),
                ('variacao', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='itens_comprados', to='core.variacaoloja', verbose_name='Variação')),
            ],
            options={
                'verbose_name': 'Item da compra',
                'verbose_name_plural': 'Itens da compra',
                'ordering': ['kit', 'id'],
            },
        ),
    ]
