# Generated by Django 5.2.12 on 2026-07-06 00:26

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0021_produtoloja_compraloja_grupoloja_variacaoloja_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='FotoProdutoLoja',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='loja/produtos/', verbose_name='Imagem')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('produto', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fotos', to='core.produtoloja', verbose_name='Produto')),
            ],
            options={
                'verbose_name': 'Foto do produto',
                'verbose_name_plural': 'Fotos do produto',
                'ordering': ['ordem', 'id'],
            },
        ),
    ]
