# Generated by Django 5.2.12 on 2026-07-06 01:31

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0023_itemcompraloja_entregue_em_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aventureiro',
            name='mensalidade_desconto_pct',
            field=models.PositiveSmallIntegerField(default=0, verbose_name='Desconto na mensalidade (%)'),
        ),
        migrations.AddField(
            model_name='aventureiro',
            name='mensalidade_isento',
            field=models.BooleanField(default=False, verbose_name='Isento de mensalidade'),
        ),
        migrations.CreateModel(
            name='ConfigMensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor_inscricao', models.DecimalField(decimal_places=2, default=30, max_digits=10, verbose_name='Valor da inscrição')),
                ('valor_mensalidade', models.DecimalField(decimal_places=2, default=30, max_digits=10, verbose_name='Valor da mensalidade')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='config_mensalidades', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de mensalidades',
                'verbose_name_plural': 'Configuração de mensalidades',
            },
        ),
        migrations.CreateModel(
            name='Mensalidade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês')),
                ('tipo', models.CharField(choices=[('inscricao', 'Inscrição'), ('mensalidade', 'Mensalidade')], default='mensalidade', max_length=12, verbose_name='Tipo')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('isento', models.BooleanField(default=False, verbose_name='Isento')),
                ('status', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], default='aberta', max_length=12, verbose_name='Situação')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('online', 'Online (site)'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('cortesia', 'Cortesia')], max_length=12, verbose_name='Forma de pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pago')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('aventureiro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensalidades', to='core.aventureiro', verbose_name='Aventureiro')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Registrado por')),
            ],
            options={
                'verbose_name': 'Mensalidade',
                'verbose_name_plural': 'Mensalidades',
                'ordering': ['ano', 'mes'],
                'unique_together': {('aventureiro', 'ano', 'mes')},
            },
        ),
    ]
