# Generated by Django 5.2.12 on 2026-07-06 02:38

import datetime
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0024_aventureiro_mensalidade_desconto_pct_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Descrição do gasto')),
                ('descricao', models.TextField(blank=True, verbose_name='Observação')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('data', models.DateField(default=datetime.date.today, verbose_name='Data')),
                ('comprovante', models.FileField(blank=True, null=True, upload_to='clube/custos/', verbose_name='Comprovante')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='custos_clube', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Custo do clube',
                'verbose_name_plural': 'Custos do clube',
                'ordering': ['-data', '-id'],
            },
        ),
    ]
