# Generated by Django 5.2.12 on 2026-07-06 02:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0025_custoclube'),
    ]

    operations = [
        migrations.CreateModel(
            name='ComprovanteCustoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('arquivo', models.FileField(upload_to='clube/custos/', verbose_name='Arquivo')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('custo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comprovantes', to='core.custoclube', verbose_name='Custo')),
            ],
            options={
                'verbose_name': 'Comprovante do custo',
                'verbose_name_plural': 'Comprovantes do custo',
                'ordering': ['id'],
            },
        ),
    ]
