# Generated by Django 5.2.12 on 2026-07-06 03:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0026_comprovantecustoclube'),
    ]

    operations = [
        migrations.AddField(
            model_name='custoclube',
            name='destino',
            field=models.CharField(choices=[('geral', 'Geral do clube'), ('loja', 'Loja')], default='geral', max_length=10, verbose_name='Destino'),
        ),
    ]
