# Generated by Django 5.2.12 on 2026-07-06 13:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0027_custoclube_destino'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CaixaClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('saldo_banco', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Saldo na conta (banco)')),
                ('a_receber', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='A receber (empréstimos/pendências)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='caixa_atualizado', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Caixa do clube',
                'verbose_name_plural': 'Caixa do clube',
            },
        ),
    ]
