# Generated by Django 5.2.12 on 2026-07-06 13:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0028_caixaclube'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='caixaclube',
            name='a_receber',
        ),
    ]
