# Generated by Django 5.2.12 on 2026-07-06 22:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0030_assinaturadocumento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MercadoPagoConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('teste', 'Teste (sandbox)'), ('producao', 'Produção')], default='teste', max_length=10, verbose_name='Modo')),
                ('access_token_teste', models.CharField(blank=True, max_length=255, verbose_name='Access Token de teste')),
                ('public_key_teste', models.CharField(blank=True, max_length=255, verbose_name='Public Key de teste')),
                ('webhook_secret_teste', models.CharField(blank=True, max_length=255, verbose_name='Assinatura secreta do webhook (teste)')),
                ('access_token_prod', models.CharField(blank=True, max_length=255, verbose_name='Access Token de produção')),
                ('public_key_prod', models.CharField(blank=True, max_length=255, verbose_name='Public Key de produção')),
                ('webhook_secret_prod', models.CharField(blank=True, max_length=255, verbose_name='Assinatura secreta do webhook (produção)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mercadopago_configs', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração do Mercado Pago',
                'verbose_name_plural': 'Configuração do Mercado Pago',
            },
        ),
        migrations.CreateModel(
            name='Pagamento',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(choices=[('loja_evento', 'Lojinha de evento'), ('loja_clube', 'Loja do Clube'), ('mensalidade', 'Mensalidades'), ('inscricao', 'Inscrição de evento')], max_length=20, verbose_name='Tipo')),
                ('forma', models.CharField(choices=[('pix', 'Pix'), ('cartao', 'Cartão de crédito')], default='pix', max_length=12, verbose_name='Forma')),
                ('referencia', models.CharField(max_length=40, unique=True, verbose_name='Referência')),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID no Mercado Pago')),
                ('modo', models.CharField(default='teste', max_length=10, verbose_name='Modo')),
                ('status', models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('estornado', 'Estornado')], default='pendente', max_length=12, verbose_name='Situação')),
                ('valor_bruto', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor bruto')),
                ('taxa', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Taxa do gateway')),
                ('valor_liquido', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor líquido (caiu no banco)')),
                ('payload', models.JSONField(blank=True, default=dict, verbose_name='Dados do que está sendo pago')),
                ('qr_code', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('qr_code_base64', models.TextField(blank=True, verbose_name='QR Code (base64)')),
                ('ticket_url', models.URLField(blank=True, max_length=500, verbose_name='Link do comprovante/QR')),
                ('finalizado', models.BooleanField(default=False, verbose_name='Finalizado')),
                ('detalhe', models.TextField(blank=True, verbose_name='Detalhe/observações do gateway')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('usuario', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pagamentos', to=settings.AUTH_USER_MODEL, verbose_name='Usuário (se logado)')),
            ],
            options={
                'verbose_name': 'Pagamento',
                'verbose_name_plural': 'Pagamentos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddField(
            model_name='pedidoloja',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='pedidos_loja', to='core.pagamento', verbose_name='Pagamento (gateway)'),
        ),
    ]
