# Generated by Django 5.2.12 on 2026-07-06 22:49

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0031_mercadopagoconfig_pagamento_pedidoloja_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mensalidade',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='mensalidades', to='core.pagamento', verbose_name='Pagamento (gateway)'),
        ),
    ]
