# Generated by Django 5.2.12 on 2026-07-06 23:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0032_mensalidade_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='compraloja',
            name='pagamento',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='compras_loja', to='core.pagamento', verbose_name='Pagamento (gateway)'),
        ),
    ]
