# Generated by Django 5.2.12 on 2026-07-07 01:07

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0034_inscricao_pagamento'),
    ]

    operations = [
        migrations.AddField(
            model_name='mercadopagoconfig',
            name='taxa_cartao_pct',
            field=models.DecimalField(decimal_places=2, default=Decimal('4.98'), max_digits=5, verbose_name='Taxa de intermediação do cartão (%)'),
        ),
    ]
