# Generated by Django 5.2.12 on 2026-07-07 02:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0035_mercadopagoconfig_taxa_cartao_pct'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='token_acerto',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Token de acerto'),
        ),
    ]
