# Generated by Django 5.2.12 on 2026-07-07 02:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0036_perfilusuario_token_acerto'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configmensalidade',
            name='mensagem_cobranca',
            field=models.TextField(blank=True, default='Olá {nome}! 👋 Aqui é do Clube de Aventureiros Pinhal Júnior.\n\nIdentificamos as seguintes mensalidades em aberto:\n{itens}\n*Total: R$ {total}*\n\nPara acertar rapidinho (Pix ou cartão), é só acessar:\n{link}\n\nQualquer dúvida, estamos à disposição. Obrigado! 💚', verbose_name='Mensagem de cobrança (WhatsApp)'),
        ),
        migrations.CreateModel(
            name='CobrancaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do envio')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês do envio')),
                ('enviada_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_disparadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Família (conta)')),
            ],
            options={
                'verbose_name': 'Cobrança enviada',
                'verbose_name_plural': 'Cobranças enviadas',
                'ordering': ['-enviada_em'],
            },
        ),
    ]
