# Generated by Django 5.2.12 on 2026-07-07 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0037_configmensalidade_mensagem_cobranca_cobrancaenviada'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmensalidade',
            name='mensagem_apelo',
            field=models.TextField(blank=True, default='Sua contribuição mantém o Clube de Aventureiros Pinhal Júnior de pé 💚 É com as mensalidades que realizamos os encontros, os eventos e as atividades que fazem a criançada crescer e viver grandes aventuras. Manter a mensalidade em dia ajuda o clube a fazer cada vez mais. Obrigado por caminhar com a gente!', verbose_name='Mensagem de apelo (área do responsável)'),
        ),
    ]
