# Generated by Django 5.2.12 on 2026-07-07 16:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0038_configmensalidade_mensagem_apelo'),
    ]

    operations = [
        migrations.AddField(
            model_name='aventureiro',
            name='demo',
            field=models.BooleanField(default=False, verbose_name='Fictício (dados de teste)'),
        ),
        migrations.AddField(
            model_name='evento',
            name='demo',
            field=models.BooleanField(default=False, verbose_name='Fictício (dados de teste)'),
        ),
    ]
