# Generated by Django 5.2.12 on 2026-07-11 10:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0039_aventureiro_demo_evento_demo'),
    ]

    operations = [
        migrations.AddField(
            model_name='fichamedica',
            name='bronquite',
            field=models.BooleanField(default=False, verbose_name='Bronquite'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='caxumba',
            field=models.BooleanField(default=False, verbose_name='Caxumba'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='coqueluche',
            field=models.BooleanField(default=False, verbose_name='Coqueluche'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='deficiente_auditivo',
            field=models.BooleanField(default=False, verbose_name='Deficiência auditiva'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='deficiente_cadeirante',
            field=models.BooleanField(default=False, verbose_name='Deficiente físico (cadeirante)'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='deficiente_fala',
            field=models.BooleanField(default=False, verbose_name='Deficiência de fala (mudez ou dificuldade)'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='deficiente_visual',
            field=models.BooleanField(default=False, verbose_name='Deficiência visual'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='difteria',
            field=models.BooleanField(default=False, verbose_name='Difteria'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='rinite',
            field=models.BooleanField(default=False, verbose_name='Rinite'),
        ),
        migrations.AddField(
            model_name='fichamedica',
            name='variola',
            field=models.BooleanField(default=False, verbose_name='Varíola'),
        ),
    ]
