# Generated by Django 5.2.12 on 2026-07-11 11:04

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0041_membrodiretoria_fichamedicadiretoria'),
    ]

    operations = [
        migrations.CreateModel(
            name='AssinaturaDocumentoDiretoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('imagem', models.ImageField(upload_to='assinaturas/%Y/%m', verbose_name='Assinatura')),
                ('titulo_documento', models.CharField(blank=True, max_length=150, verbose_name='Título do documento')),
                ('texto_documento', models.TextField(blank=True, verbose_name='Texto do termo assinado')),
                ('assinante_nome', models.CharField(blank=True, max_length=150, verbose_name='Assinado por')),
                ('assinante_cpf', models.CharField(blank=True, max_length=20, verbose_name='CPF de quem assinou')),
                ('assinado_em', models.DateTimeField(auto_now_add=True, verbose_name='Assinado em')),
                ('documento', models.CharField(choices=[('compromisso', 'Compromisso de voluntário'), ('declaracao_medica', 'Declaração médica'), ('autorizacao_imagem', 'Termo de autorização de imagem')], max_length=30, verbose_name='Documento')),
                ('membro', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='assinaturas', to='core.membrodiretoria', verbose_name='Membro da diretoria')),
            ],
            options={
                'verbose_name': 'Assinatura de documento (diretoria)',
                'verbose_name_plural': 'Assinaturas de documentos (diretoria)',
                'ordering': ['documento'],
                'unique_together': {('membro', 'documento')},
            },
        ),
    ]
