# Generated by Django 5.2.12 on 2026-07-11 21:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0042_assinaturadocumentodiretoria'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenAIConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('api_key', models.CharField(blank=True, max_length=255, verbose_name='Chave da API (token)')),
                ('modelo', models.CharField(blank=True, default='gpt-4o-mini', help_text='Nome do modelo da OpenAI (ex.: gpt-4o-mini, gpt-4o).', max_length=80, verbose_name='Modelo')),
                ('base_url', models.CharField(blank=True, default='https://api.openai.com/v1', max_length=200, verbose_name='URL base da API')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='openai_configs', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração da IA',
                'verbose_name_plural': 'Configuração da IA',
            },
        ),
    ]
