# Generated by Django 5.2.12 on 2026-07-11 21:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0043_openaiconfig'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openaiconfig',
            name='base_url',
        ),
        migrations.RemoveField(
            model_name='openaiconfig',
            name='modelo',
        ),
        migrations.AddField(
            model_name='openaiconfig',
            name='chamadas',
            field=models.PositiveIntegerField(default=0, verbose_name='Chamadas à IA'),
        ),
        migrations.AddField(
            model_name='openaiconfig',
            name='tokens_cache',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tokens de entrada em cache'),
        ),
        migrations.AddField(
            model_name='openaiconfig',
            name='tokens_completion',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tokens de saída'),
        ),
        migrations.AddField(
            model_name='openaiconfig',
            name='tokens_prompt',
            field=models.PositiveBigIntegerField(default=0, verbose_name='Tokens de entrada'),
        ),
    ]
