# Generated by Django 5.2.12 on 2026-07-11 21:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0044_remove_openaiconfig_base_url_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configmensalidade',
            name='cobranca_via_ia',
            field=models.BooleanField(default=False, verbose_name='Cobrança gerada pela IA'),
        ),
        migrations.AddField(
            model_name='configmensalidade',
            name='prompt_cobranca_ia',
            field=models.TextField(blank=True, default='Você é o tesoureiro do Clube de Aventureiros Pinhal Júnior e vai escrever uma mensagem de WhatsApp para {nome}, lembrando com gentileza de mensalidades em aberto.\n\nMensalidades em aberto:\n{itens}\nTotal: R$ {total}\nLink para pagar fácil (Pix ou cartão): {link}\n\nEscreva uma mensagem CURTA, objetiva e MUITO educada, em português do Brasil, agradecendo a família pela colaboração e parceria com o clube. Inclua o link de pagamento. Use no máximo 1 ou 2 emojis discretos. NÃO invente valores, datas ou informações além das acima. Responda apenas com o texto final da mensagem, sem aspas nem comentários.', verbose_name='Prompt da cobrança (IA)'),
        ),
    ]
