# Generated by Django 5.2.12 on 2026-07-11 22:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0045_configmensalidade_cobranca_via_ia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='cobranca_whatsapp_origem',
            field=models.CharField(blank=True, choices=[('pai', 'Pai'), ('mae', 'Mãe'), ('resp', 'Responsável legal')], max_length=4, verbose_name='WhatsApp de cobrança (origem)'),
        ),
        migrations.AlterField(
            model_name='configmensalidade',
            name='prompt_cobranca_ia',
            field=models.TextField(blank=True, default='Você é o tesoureiro do Clube de Aventureiros Pinhal Júnior e vai escrever uma mensagem de WhatsApp para {nome}, lembrando com gentileza de mensalidades em aberto.\n\nMensalidades em aberto:\n{itens}\nTotal: R$ {total}\nLink para pagar fácil (Pix ou cartão): {link}\n\nEscreva uma mensagem CURTA, objetiva e MUITO educada, em português do Brasil, agradecendo a família pela colaboração e parceria com o clube.\n\nFORMATO (use quebras de linha de verdade, com uma linha em branco entre os blocos):\n1) uma saudação inicial;\n2) a lista de mensalidades em aberto, cada item em sua própria linha;\n3) o total;\n4) o link de pagamento;\n5) um agradecimento final.\n\nUse no máximo 1 ou 2 emojis discretos. NÃO invente valores, datas ou informações além das acima. Responda apenas com o texto final da mensagem, sem aspas nem comentários.', verbose_name='Prompt da cobrança (IA)'),
        ),
    ]
