# Generated by Django 5.2.12 on 2026-07-12 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0046_perfilusuario_cobranca_whatsapp_origem_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='GrupoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=100, unique=True, verbose_name='ID do grupo')),
                ('nome', models.CharField(blank=True, max_length=200, verbose_name='Nome do grupo')),
                ('tamanho', models.PositiveIntegerField(default=0, verbose_name='Participantes')),
                ('usar_liberacao', models.BooleanField(default=False, verbose_name='Grupo dos pais (liberação)')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Grupo do WhatsApp',
                'verbose_name_plural': 'Grupos do WhatsApp',
                'ordering': ['nome'],
            },
        ),
    ]
