# Generated by Django 5.2.12 on 2026-07-12 00:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0047_grupowhatsapp'),
    ]

    operations = [
        migrations.CreateModel(
            name='WhatsappWebhookEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(default='unknown', max_length=80, verbose_name='Tipo de evento')),
                ('instance_id', models.CharField(blank=True, default='', max_length=120, verbose_name='Instância')),
                ('phone', models.CharField(blank=True, default='', max_length=40, verbose_name='Telefone do remetente')),
                ('contact_name', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome do contato')),
                ('message_id', models.CharField(blank=True, default='', max_length=160, verbose_name='ID da mensagem')),
                ('message_type', models.CharField(default='unknown', max_length=60, verbose_name='Tipo da mensagem')),
                ('message_text', models.TextField(blank=True, default='', verbose_name='Texto')),
                ('from_me', models.BooleanField(default=False, verbose_name='Enviada por mim')),
                ('is_group', models.BooleanField(default=False, verbose_name='De grupo')),
                ('chat_id', models.CharField(blank=True, default='', max_length=120, verbose_name='ID da conversa')),
                ('raw_payload', models.JSONField(default=dict, verbose_name='Payload cru')),
                ('recebido_em', models.DateTimeField(auto_now_add=True, verbose_name='Recebido em')),
            ],
            options={
                'verbose_name': 'Evento de webhook (WhatsApp)',
                'verbose_name_plural': 'Eventos de webhook (WhatsApp)',
                'ordering': ['-recebido_em'],
            },
        ),
    ]
