# Generated by Django 5.2.12 on 2026-07-12 01:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0048_whatsappwebhookevent'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='autorizacao_recebida_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Autorização recebida em'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='ultima_msg_whatsapp_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Última mensagem recebida (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='mensagem_autorizacao',
            field=models.TextField(blank=True, default='Autorizo o Clube de Aventureiros Pinhal Júnior a me enviar mensagens.', verbose_name='Mensagem de autorização (o responsável envia)'),
        ),
    ]
