# Generated by Django 5.2.12 on 2026-07-12 01:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0049_perfilusuario_autorizacao_recebida_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='numero_clube',
            field=models.CharField(blank=True, max_length=30, verbose_name='Número do WhatsApp do clube'),
        ),
    ]
