# Generated by Django 5.2.12 on 2026-07-12 01:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0050_whatsappconfig_numero_clube'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='reengajado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Reengajado em'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='mensagem_reengajamento',
            field=models.TextField(blank=True, default='Oi! 👋 Notei que não tive resposta nas últimas mensagens. Você quer continuar recebendo as notificações do Clube de Aventureiros Pinhal Júnior? Se sim, é só responder esta mensagem. 💚', verbose_name='Mensagem de reengajamento'),
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='reengajar_dias',
            field=models.PositiveIntegerField(default=30, verbose_name='Reengajar após (dias sem resposta)'),
        ),
    ]
