# Generated by Django 5.2.12 on 2026-07-12 02:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0051_perfilusuario_reengajado_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='whatsappconfig',
            name='resposta_autorizacao',
            field=models.TextField(blank=True, default='Prontinho! ✅ Você já está autorizado(a) a receber as notificações do Clube de Aventureiros Pinhal Júnior. Obrigado pela parceria! 💚', verbose_name='Resposta automática à autorização'),
        ),
    ]
