# Generated by Django 5.2.12 on 2026-07-12 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0052_whatsappconfig_resposta_autorizacao'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContatoWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=20, unique=True, verbose_name='Número (normalizado)')),
                ('nome', models.CharField(blank=True, default='', max_length=150, verbose_name='Nome do contato')),
                ('primeira_msg_em', models.DateTimeField(auto_now_add=True, verbose_name='Primeira mensagem em')),
                ('ultima_msg_em', models.DateTimeField(blank=True, null=True, verbose_name='Última mensagem em')),
                ('total_msgs', models.PositiveIntegerField(default=0, verbose_name='Mensagens recebidas')),
                ('autorizou_em', models.DateTimeField(blank=True, null=True, verbose_name='Autorizou em')),
            ],
            options={
                'verbose_name': 'Contato do WhatsApp',
                'verbose_name_plural': 'Contatos do WhatsApp',
                'ordering': ['-ultima_msg_em'],
            },
        ),
        migrations.AddField(
            model_name='whatsappconfig',
            name='notificar_janela_dias',
            field=models.PositiveIntegerField(default=60, verbose_name='Janela de envio de notificações (dias)'),
        ),
        migrations.CreateModel(
            name='TemplateNotificacao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=40, unique=True, verbose_name='Tipo')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('usar_ia', models.BooleanField(default=False, verbose_name='Redigir com IA')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='Texto do sistema')),
                ('prompt_ia', models.TextField(blank=True, default='', verbose_name='Prompt da IA')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_notificacao', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
                ('avisos_internos_para', models.ManyToManyField(blank=True, related_name='notificacoes_internas', to=settings.AUTH_USER_MODEL, verbose_name='Recebem o aviso interno')),
            ],
            options={
                'verbose_name': 'Template de notificação',
                'verbose_name_plural': 'Templates de notificação',
            },
        ),
    ]
