# Generated by Django 5.2.12 on 2026-07-13 02:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0053_contatowhatsapp_whatsappconfig_notificar_janela_dias_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aventureiro',
            name='ativo',
            field=models.BooleanField(db_index=True, default=True, verbose_name='Ativo (frequenta o clube)'),
        ),
        migrations.AlterField(
            model_name='aventureiro',
            name='demo',
            field=models.BooleanField(db_index=True, default=False, verbose_name='Fictício (dados de teste)'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='ano',
            field=models.PositiveIntegerField(db_index=True, verbose_name='Ano'),
        ),
        migrations.AlterField(
            model_name='mensalidade',
            name='status',
            field=models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=12, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='status',
            field=models.CharField(choices=[('pendente', 'Aguardando pagamento'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('expirado', 'Expirado'), ('estornado', 'Estornado')], db_index=True, default='pendente', max_length=12, verbose_name='Situação'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('loja_evento', 'Lojinha de evento'), ('loja_clube', 'Loja do Clube'), ('mensalidade', 'Mensalidades'), ('inscricao', 'Inscrição de evento')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
    ]
