# Generated by Django 5.2.16 on 2026-07-31 02:35

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0054_alter_aventureiro_ativo_alter_aventureiro_demo_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('host', models.CharField(blank=True, default='smtp.gmail.com', max_length=120, verbose_name='Servidor SMTP')),
                ('porta', models.PositiveIntegerField(default=587, verbose_name='Porta')),
                ('seguranca', models.CharField(choices=[('tls', 'STARTTLS (porta 587)'), ('ssl', 'SSL/TLS (porta 465)'), ('nenhuma', 'Nenhuma')], default='tls', max_length=10, verbose_name='Segurança')),
                ('usuario', models.CharField(blank=True, max_length=254, verbose_name='Conta (e-mail)')),
                ('senha', models.CharField(blank=True, max_length=255, verbose_name='Senha de app')),
                ('remetente_nome', models.CharField(blank=True, default='Clube de Aventureiros Pinhal Júnior', max_length=120, verbose_name='Nome do remetente')),
                ('enviados', models.PositiveIntegerField(default=0, verbose_name='E-mails enviados')),
                ('falhas', models.PositiveIntegerField(default=0, verbose_name='Falhas de envio')),
                ('ultimo_envio_em', models.DateTimeField(blank=True, null=True, verbose_name='Último envio')),
                ('ultimo_erro', models.TextField(blank=True, default='', verbose_name='Último erro')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_configs', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração de e-mail',
                'verbose_name_plural': 'Configuração de e-mail',
            },
        ),
    ]
