# Generated by Django 5.2.16 on 2026-07-31 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0055_emailconfig'),
    ]

    operations = [
        migrations.AddField(
            model_name='emailconfig',
            name='reply_to',
            field=models.EmailField(blank=True, max_length=254, verbose_name='Responder para'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='rodape',
            field=models.TextField(blank=True, default='Clube de Aventureiros Pinhal Júnior\nVocê recebeu este e-mail porque faz parte do cadastro do clube.', verbose_name='Rodapé'),
        ),
        migrations.AddField(
            model_name='emailconfig',
            name='site_url',
            field=models.URLField(blank=True, default='https://pinhaljunior.com.br', verbose_name='Endereço público do site'),
        ),
        migrations.AddField(
            model_name='templatenotificacao',
            name='assunto',
            field=models.CharField(blank=True, default='', max_length=200, verbose_name='Assunto do e-mail'),
        ),
        migrations.AddField(
            model_name='templatenotificacao',
            name='enviar_email',
            field=models.BooleanField(default=False, verbose_name='Enviar por e-mail'),
        ),
        migrations.AddField(
            model_name='templatenotificacao',
            name='enviar_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Enviar por WhatsApp'),
        ),
        migrations.CreateModel(
            name='ContatoEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endereco', models.EmailField(max_length=254, unique=True, verbose_name='E-mail')),
                ('nome', models.CharField(blank=True, max_length=150, verbose_name='Nome')),
                ('descadastrado_em', models.DateTimeField(blank=True, null=True, verbose_name='Descadastrado em')),
                ('bounce_em', models.DateTimeField(blank=True, null=True, verbose_name='Recusado em')),
                ('bounce_motivo', models.CharField(blank=True, max_length=300, verbose_name='Motivo da recusa')),
                ('enviados', models.PositiveIntegerField(default=0, verbose_name='E-mails enviados')),
                ('ultimo_envio_em', models.DateTimeField(blank=True, null=True, verbose_name='Último envio')),
                ('token', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Token de descadastro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
            ],
            options={
                'verbose_name': 'Contato de e-mail',
                'verbose_name_plural': 'Contatos de e-mail',
                'ordering': ['endereco'],
                'indexes': [models.Index(fields=['descadastrado_em'], name='core_contat_descada_07798a_idx'), models.Index(fields=['bounce_em'], name='core_contat_bounce__784ba7_idx')],
            },
        ),
    ]
