# Generated by Django 5.2.16 on 2026-07-31 16:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0056_emailconfig_reply_to_emailconfig_rodape_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='cobrancaenviada',
            name='canal',
            field=models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], db_index=True, default='whatsapp', max_length=10, verbose_name='Canal'),
        ),
        migrations.AddField(
            model_name='configmensalidade',
            name='assunto_cobranca_email',
            field=models.CharField(blank=True, default='Mensalidades em aberto — Clube de Aventureiros Pinhal Júnior', max_length=200, verbose_name='Assunto da cobrança (e-mail)'),
        ),
    ]
