# Generated by Django 5.2.16 on 2026-07-31 17:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0057_cobrancaenviada_canal_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='LogEmail',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('para', models.EmailField(max_length=254, verbose_name='Destinatário')),
                ('assunto', models.CharField(blank=True, default='', max_length=200, verbose_name='Assunto')),
                ('origem', models.CharField(blank=True, default='', help_text="Tipo da notificação, 'cobranca' ou 'teste'.", max_length=40, verbose_name='Origem')),
                ('ok', models.BooleanField(default=False, verbose_name='Enviado')),
                ('detalhe', models.CharField(blank=True, default='', max_length=300, verbose_name='Detalhe / erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
            ],
            options={
                'verbose_name': 'E-mail enviado',
                'verbose_name_plural': 'E-mails enviados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='core_logema_criado__bbf41b_idx')],
            },
        ),
    ]
