# Generated by Django 5.2.16 on 2026-08-01 22:02

from django.db import migrations, models


def marcar_confirmacoes_antigas(apps, schema_editor):
    """Quem JÁ estava autorizado é tratado como já confirmado.

    Sem isso, o campo nasceria vazio para todo mundo e a próxima mensagem de cada
    pessoa já autorizada dispararia uma confirmação — gente que recebeu a resposta
    semanas atrás levaria uma segunda, do nada. O passado fica fechado; o retry
    passa a valer só para autorizações daqui em diante."""
    PerfilUsuario = apps.get_model("core", "PerfilUsuario")
    PerfilUsuario.objects.filter(
        autorizacao_recebida_em__isnull=False,
        confirmacao_autorizacao_em__isnull=True,
    ).update(confirmacao_autorizacao_em=models.F("autorizacao_recebida_em"))


def desfazer(apps, schema_editor):
    """Reversão: o campo some junto com o AddField, nada a limpar."""


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0058_logemail'),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='confirmacao_autorizacao_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Confirmação da autorização enviada em'),
        ),
        migrations.RunPython(marcar_confirmacoes_antigas, desfazer),
    ]
