# Generated by Django 5.2.16 on 2026-08-01 22:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0059_perfilusuario_confirmacao_autorizacao_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='aventureiro',
            name='mae_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento da mãe'),
        ),
        migrations.AddField(
            model_name='aventureiro',
            name='pai_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento do pai'),
        ),
        migrations.AddField(
            model_name='aventureiro',
            name='resp_data_nascimento',
            field=models.DateField(blank=True, null=True, verbose_name='Data de nascimento do responsável legal'),
        ),
        migrations.CreateModel(
            name='TemplateAniversario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tipo', models.CharField(max_length=20, unique=True, verbose_name='Perfil')),
                ('ativo', models.BooleanField(default=False, verbose_name='Ativo')),
                ('mensagem', models.TextField(blank=True, default='', verbose_name='Mensagem')),
                ('assunto', models.CharField(blank=True, default='', max_length=200, verbose_name='Assunto do e-mail')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='templates_aniversario', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Mensagem de aniversário',
                'verbose_name_plural': 'Mensagens de aniversário',
            },
        ),
    ]
