# Generated by Django 5.2.16 on 2026-08-01 23:23

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0060_aventureiro_mae_data_nascimento_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='templateaniversario',
            name='enviar_email',
            field=models.BooleanField(default=True, verbose_name='Enviar por e-mail'),
        ),
        migrations.AddField(
            model_name='templateaniversario',
            name='enviar_whatsapp',
            field=models.BooleanField(default=True, verbose_name='Enviar por WhatsApp'),
        ),
        migrations.CreateModel(
            name='EnvioAniversario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chave', models.CharField(db_index=True, max_length=120, verbose_name='Identidade da pessoa')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome')),
                ('perfil', models.CharField(max_length=20, verbose_name='Perfil')),
                ('ano', models.PositiveIntegerField(verbose_name='Ano do aniversário')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], max_length=10, verbose_name='Canal')),
                ('destino', models.CharField(blank=True, default='', max_length=254, verbose_name='Destino')),
                ('ok', models.BooleanField(default=False, verbose_name='Enviado')),
                ('detalhe', models.CharField(blank=True, default='', max_length=300, verbose_name='Detalhe / erro')),
                ('manual', models.BooleanField(default=False, verbose_name='Envio manual')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('enviado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='aniversarios_enviados', to=settings.AUTH_USER_MODEL, verbose_name='Enviado por')),
            ],
            options={
                'verbose_name': 'Aniversário enviado',
                'verbose_name_plural': 'Aniversários enviados',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['ano', 'chave'], name='core_envioa_ano_748c9a_idx')],
                'constraints': [models.UniqueConstraint(condition=models.Q(('ok', True)), fields=('chave', 'ano', 'canal'), name='aniversario_unico_por_ano_e_canal')],
            },
        ),
    ]
