# Generated by Django 6.0.5 on 2026-08-12 14:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0061_templateaniversario_enviar_email_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='formas_pagamento_online',
            field=models.CharField(choices=[('ambos', 'Pix e cartão de crédito'), ('pix', 'Somente Pix'), ('cartao', 'Somente cartão de crédito')], default='ambos', max_length=10, verbose_name='Formas de pagamento no site'),
        ),
    ]
