# Generated by Django 6.0.5 on 2026-08-12 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0062_evento_formas_pagamento_online'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='ativo',
            field=models.BooleanField(default=True, verbose_name='Evento ativo'),
        ),
    ]
