# Generated by Django 6.0.5 on 2026-08-12 20:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0063_evento_ativo'),
    ]

    operations = [
        migrations.CreateModel(
            name='MensagemWhatsapp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, verbose_name='Número (destino)')),
                ('nome', models.CharField(blank=True, default='', help_text='Nome conhecido na hora do envio (snapshot).', max_length=120, verbose_name='Para quem')),
                ('origem', models.CharField(blank=True, default='', help_text="Tipo da notificação, 'cobranca', 'reengajamento', 'teste'…", max_length=40, verbose_name='Origem')),
                ('message_id', models.CharField(blank=True, db_index=True, default='', max_length=120, verbose_name='ID da mensagem (W-API)')),
                ('status', models.CharField(choices=[('falhou', 'Falhou no envio'), ('aceita', 'Enviada (sem confirmação)'), ('enviada', 'Enviada'), ('entregue', 'Entregue'), ('lida', 'Lida'), ('nao_entregue', 'Não entregue')], db_index=True, default='aceita', max_length=15, verbose_name='Situação')),
                ('detalhe', models.CharField(blank=True, default='', max_length=300, verbose_name='Detalhe / erro')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Quando')),
                ('status_em', models.DateTimeField(blank=True, null=True, verbose_name='Última atualização de status')),
            ],
            options={
                'verbose_name': 'Mensagem de WhatsApp',
                'verbose_name_plural': 'Mensagens de WhatsApp',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['-criado_em'], name='core_mensag_criado__25f9f0_idx')],
            },
        ),
    ]
