# Generated by Django 5.2.16 on 2026-08-13 23:44

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0064_mensagemwhatsapp'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='instrucoes_pagamento_fora',
            field=models.TextField(blank=True, verbose_name='Orientação de pagamento'),
        ),
        migrations.AddField(
            model_name='evento',
            name='pagamento_por_fora',
            field=models.BooleanField(default=False, verbose_name='Pagamento é feito direto ao evento (não entra no caixa do clube)'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pagamento_externo',
            field=models.BooleanField(default=False, verbose_name='Pago direto ao evento (fora do caixa)'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pago_externo_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Pagamento confirmado em'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='pago_externo_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='inscricoes_baixadas', to=settings.AUTH_USER_MODEL, verbose_name='Baixa registrada por'),
        ),
        migrations.AddField(
            model_name='pedidoloja',
            name='pagamento_externo',
            field=models.BooleanField(default=False, verbose_name='Pago direto ao evento (fora do caixa)'),
        ),
    ]
