# Generated by Django 5.2.16 on 2026-08-14 01:43
#
# O "pago direto ao evento" deixou de ser sim/não do evento e passou a ser
# **por forma de pagamento** (dá para cobrar o cartão pelo site e deixar só o
# Pix por fora). A ordem aqui importa: cria o campo novo, converte o que já
# estava marcado e só então remove o antigo — quem tinha a chave ligada fica
# com TODAS as formas por fora, que é o que a chave significava.

from django.db import migrations, models


def marcar_todas_as_formas(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")
    Evento.objects.filter(pagamento_por_fora=True).update(
        formas_pagamento_fora="ambos"
    )


def voltar_para_a_chave(apps, schema_editor):
    Evento = apps.get_model("core", "Evento")
    Evento.objects.exclude(formas_pagamento_fora="nenhuma").update(
        pagamento_por_fora=True
    )


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0065_evento_instrucoes_pagamento_fora_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='formas_pagamento_fora',
            field=models.CharField(choices=[('nenhuma', 'Nenhuma — tudo cobrado pelo site'), ('pix', 'Pix'), ('cartao', 'Cartão de crédito'), ('ambos', 'Pix e cartão de crédito')], default='nenhuma', max_length=10, verbose_name='Formas pagas direto ao evento'),
        ),
        migrations.RunPython(marcar_todas_as_formas, voltar_para_a_chave),
        migrations.RemoveField(
            model_name='evento',
            name='pagamento_por_fora',
        ),
    ]
