# Generated by Django 5.2.16 on 2026-08-16 00:55

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0066_formas_pagamento_fora'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='notificar_inscricoes',
            field=models.BooleanField(default=False, verbose_name='Avisar a diretoria a cada inscrição'),
        ),
        migrations.AddField(
            model_name='evento',
            name='notificar_inscricoes_para',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='eventos_avisos_inscricao', to=settings.AUTH_USER_MODEL, verbose_name='Quem recebe o aviso'),
        ),
    ]
