# Generated by Django 6.0.5 on 2026-08-17 19:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0067_aviso_inscricao_evento'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parcelas_diretoria',
            field=models.PositiveSmallIntegerField(default=1, verbose_name='Parcelas para a diretoria'),
        ),
        migrations.AddField(
            model_name='inscricao',
            name='token_parcelas',
            field=models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Token das parcelas'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('loja_evento', 'Lojinha de evento'), ('loja_clube', 'Loja do Clube'), ('mensalidade', 'Mensalidades'), ('inscricao', 'Inscrição de evento'), ('parcela_inscricao', 'Parcela de inscrição')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='ParcelaInscricao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Parcela')),
                ('total', models.PositiveSmallIntegerField(default=1, verbose_name='De (total de parcelas)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=12, verbose_name='Situação')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('online', 'Online (site)'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('cortesia', 'Cortesia')], max_length=12, verbose_name='Forma de pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pago')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('inscricao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.inscricao', verbose_name='Inscrição')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_inscricao', to='core.pagamento', verbose_name='Pagamento (gateway)')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_inscricao_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Baixa registrada por')),
            ],
            options={
                'verbose_name': 'Parcela da inscrição',
                'verbose_name_plural': 'Parcelas da inscrição',
                'ordering': ['numero'],
                'unique_together': {('inscricao', 'numero')},
            },
        ),
    ]
