# Generated by Django 6.0.5 on 2026-08-17 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0068_parcelamento_diretoria_evento'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='inscricao_limite_diretoria',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo limite para a diretoria'),
        ),
    ]
