# Generated by Django 6.0.5 on 2026-08-20 20:08
#
# A 1ª parcela do valor da diretoria passou a ser configurável por evento:
# cobrada na inscrição (como sempre foi) ou jogada para o mês seguinte, dia 10 —
# neste caso a inscrição é concluída sem pagar nada da parte da diretoria.
#
# Por isso a parcela ganhou a flag `no_ato`: "esta parcela entrou no caixa junto
# da inscrição". Antes dava para deduzir pelo número (a 1ª era sempre a do ato);
# agora não dá mais. O passo de dados marca a flag nas parcelas que já existem —
# todas elas foram cobradas no ato —, senão o extrato passaria a contar a 1ª
# parcela duas vezes (na linha da inscrição e como lançamento próprio).

from django.db import migrations, models


def marcar_primeiras_como_cobradas_no_ato(apps, schema_editor):
    ParcelaInscricao = apps.get_model("core", "ParcelaInscricao")
    ParcelaInscricao.objects.filter(numero=1).update(no_ato=True)


def desmarcar_todas(apps, schema_editor):
    ParcelaInscricao = apps.get_model("core", "ParcelaInscricao")
    ParcelaInscricao.objects.update(no_ato=False)


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0069_prazo_inscricao_diretoria'),
    ]

    operations = [
        migrations.AddField(
            model_name='evento',
            name='parcelas_diretoria_primeira',
            field=models.CharField(choices=[('ato', 'Cobrar a 1ª parcela na inscrição'), ('proximo_mes', 'Jogar a 1ª parcela para o mês seguinte (dia 10)')], default='ato', max_length=12, verbose_name='1ª parcela da diretoria'),
        ),
        migrations.AddField(
            model_name='parcelainscricao',
            name='no_ato',
            field=models.BooleanField(default=False, verbose_name='Cobrada no ato da inscrição'),
        ),
        migrations.RunPython(
            marcar_primeiras_como_cobradas_no_ato, desmarcar_todas
        ),
    ]
