# Generated by Django 5.2.16 on 2026-09-07 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0070_parcela_primeira_proximo_mes'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='configmensalidade',
            name='assunto_cobranca_parcela_email',
            field=models.CharField(blank=True, default='Parcelas em aberto — Clube de Aventureiros Pinhal Júnior', max_length=200, verbose_name='Assunto da cobrança de parcelas (e-mail)'),
        ),
        migrations.AddField(
            model_name='configmensalidade',
            name='cobranca_parcela_via_ia',
            field=models.BooleanField(default=False, verbose_name='Cobrança de parcelas gerada pela IA'),
        ),
        migrations.AddField(
            model_name='configmensalidade',
            name='mensagem_cobranca_parcela',
            field=models.TextField(blank=True, default='Olá {nome}! 👋 Aqui é do Clube de Aventureiros Pinhal Júnior.\n\nPassando para lembrar das parcelas em aberto:\n{itens}\n*Total: R$ {total}*\n\nPara acertar rapidinho (Pix ou cartão), é só acessar:\n{link}\n\nQualquer dúvida, estamos à disposição. Obrigado! 💚', verbose_name='Mensagem de cobrança de parcelas (WhatsApp)'),
        ),
        migrations.AddField(
            model_name='configmensalidade',
            name='prompt_cobranca_parcela_ia',
            field=models.TextField(blank=True, default='Você é o tesoureiro do Clube de Aventureiros Pinhal Júnior e vai escrever uma mensagem de WhatsApp para {nome}, lembrando com gentileza de parcelas em aberto de um acerto combinado com o clube.\n\nParcelas em aberto:\n{itens}\nTotal: R$ {total}\nLink para pagar fácil (Pix ou cartão): {link}\n\nEscreva uma mensagem CURTA, objetiva e MUITO educada, em português do Brasil.\n\nFORMATO (use quebras de linha de verdade, com uma linha em branco entre os blocos):\n1) uma saudação inicial;\n2) a lista de parcelas em aberto, cada item em sua própria linha, com o vencimento;\n3) o total;\n4) o link de pagamento;\n5) um agradecimento final.\n\nUse no máximo 1 ou 2 emojis discretos. NÃO invente valores, datas ou informações além das acima. Responda apenas com o texto final da mensagem, sem aspas nem comentários.', verbose_name='Prompt da cobrança de parcelas (IA)'),
        ),
        migrations.AlterField(
            model_name='pagamento',
            name='tipo',
            field=models.CharField(choices=[('loja_evento', 'Lojinha de evento'), ('loja_clube', 'Loja do Clube'), ('mensalidade', 'Mensalidades'), ('inscricao', 'Inscrição de evento'), ('parcela_inscricao', 'Parcela de inscrição'), ('parcela_clube', 'Parcela lançada pelo clube')], db_index=True, max_length=20, verbose_name='Tipo'),
        ),
        migrations.CreateModel(
            name='CobrancaParcelaEnviada',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('canal', models.CharField(choices=[('whatsapp', 'WhatsApp'), ('email', 'E-mail')], default='whatsapp', max_length=10, verbose_name='Canal')),
                ('ano', models.PositiveIntegerField(db_index=True, verbose_name='Ano do envio')),
                ('mes', models.PositiveSmallIntegerField(verbose_name='Mês do envio')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Enviada em')),
                ('enviada_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='cobrancas_parcela_enviadas', to=settings.AUTH_USER_MODEL, verbose_name='Enviada por')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cobrancas_parcela_recebidas', to=settings.AUTH_USER_MODEL, verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Cobrança de parcelas enviada',
                'verbose_name_plural': 'Cobranças de parcelas enviadas',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelamentoClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('descricao', models.CharField(max_length=150, verbose_name='Descrição')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('valor_total', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor total')),
                ('qtd_parcelas', models.PositiveSmallIntegerField(default=1, verbose_name='Parcelas')),
                ('status', models.CharField(choices=[('ativo', 'Ativo'), ('cancelado', 'Cancelado')], db_index=True, default='ativo', max_length=12, verbose_name='Situação')),
                ('token', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='Token do link')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('aventureiro', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamentos', to='core.aventureiro', verbose_name='Aventureiro (opcional)')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamentos_criados', to=settings.AUTH_USER_MODEL, verbose_name='Lançado por')),
                ('evento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelamentos', to='core.evento', verbose_name='Evento (opcional)')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelamentos', to=settings.AUTH_USER_MODEL, verbose_name='Conta (responsável/diretoria)')),
            ],
            options={
                'verbose_name': 'Parcelamento do clube',
                'verbose_name_plural': 'Parcelamentos do clube',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='ParcelaClube',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Parcela')),
                ('total', models.PositiveSmallIntegerField(default=1, verbose_name='De (total de parcelas)')),
                ('valor', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Valor')),
                ('vencimento', models.DateField(blank=True, null=True, verbose_name='Vencimento')),
                ('status', models.CharField(choices=[('aberta', 'Em aberto'), ('paga', 'Paga'), ('cancelada', 'Cancelada')], db_index=True, default='aberta', max_length=12, verbose_name='Situação')),
                ('forma_pagamento', models.CharField(blank=True, choices=[('online', 'Online (site)'), ('dinheiro', 'Dinheiro'), ('pix', 'Pix'), ('cartao', 'Cartão'), ('cortesia', 'Cortesia')], max_length=12, verbose_name='Forma de pagamento')),
                ('valor_pago', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True, verbose_name='Valor pago')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_clube', to='core.pagamento', verbose_name='Pagamento (gateway)')),
                ('registrado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='parcelas_clube_registradas', to=settings.AUTH_USER_MODEL, verbose_name='Baixa registrada por')),
                ('parcelamento', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parcelas', to='core.parcelamentoclube', verbose_name='Parcelamento')),
            ],
            options={
                'verbose_name': 'Parcela do clube',
                'verbose_name_plural': 'Parcelas do clube',
                'ordering': ['numero'],
                'unique_together': {('parcelamento', 'numero')},
            },
        ),
    ]
