# Generated by Django 5.2.16 on 2026-09-13 01:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0071_parcelamento_clube'),
    ]

    operations = [
        migrations.AlterField(
            model_name='configmensalidade',
            name='mensagem_cobranca_parcela',
            field=models.TextField(blank=True, default='Olá {nome}! 👋 Aqui é do Clube de Aventureiros Pinhal Júnior.\n\nPassando para lembrar das parcelas em aberto:\n{itens}\n*Total: R$ {total}*\n\n🎪 Referente a: *{evento}*\n🔗 Página do evento: {link_evento}\n\nPara acertar rapidinho (Pix ou cartão), é só acessar:\n{link}\n\nQualquer dúvida, estamos à disposição. Obrigado! 💚', verbose_name='Mensagem de cobrança de parcelas (WhatsApp)'),
        ),
        migrations.AlterField(
            model_name='configmensalidade',
            name='prompt_cobranca_parcela_ia',
            field=models.TextField(blank=True, default='Você é o tesoureiro do Clube de Aventureiros Pinhal Júnior e vai escrever uma mensagem de WhatsApp para {nome}, lembrando com gentileza de parcelas em aberto de um acerto combinado com o clube.\n\nParcelas em aberto:\n{itens}\nTotal: R$ {total}\nLink para pagar fácil (Pix ou cartão): {link}\nEvento a que o acerto se refere: {evento}\nPágina desse evento: {link_evento}\n\nEscreva uma mensagem CURTA, objetiva e MUITO educada, em português do Brasil.\n\nFORMATO (use quebras de linha de verdade, com uma linha em branco entre os blocos):\n1) uma saudação inicial;\n2) a lista de parcelas em aberto, cada item em sua própria linha, com o vencimento;\n3) o total;\n4) o link de pagamento;\n5) um agradecimento final.\n\nSe acima houver um evento, cite o NOME dele numa frase e inclua a página do evento somente se ela também estiver acima; se não houver, não mencione evento nenhum.\n\nUse no máximo 1 ou 2 emojis discretos. NÃO invente valores, datas ou informações além das acima. Responda apenas com o texto final da mensagem, sem aspas nem comentários.', verbose_name='Prompt da cobrança de parcelas (IA)'),
        ),
    ]
