# Generated by Django 5.2.16 on 2026-09-13 02:19

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0072_alter_configmensalidade_mensagem_cobranca_parcela_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='perfilusuario',
            name='liberacao_diretoria_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Cadastro de diretoria liberado em'),
        ),
        migrations.AddField(
            model_name='perfilusuario',
            name='liberacao_diretoria_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='liberacoes_diretoria', to=settings.AUTH_USER_MODEL, verbose_name='Liberado por'),
        ),
    ]
