# Generated by Django 5.2.16 on 2026-09-17 00:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0073_perfilusuario_liberacao_diretoria_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='parcelamentoclube',
            name='pessoa',
            field=models.CharField(blank=True, max_length=150, verbose_name='Pessoa do acerto'),
        ),
    ]
