from django.urls import path

from . import views

app_name = "core"

urlpatterns = [
    path("", views.login_view, name="login"),
    path("sair/", views.sair_view, name="sair"),
    path("inicio/", views.inicio_view, name="inicio"),
    path(
        "meus-dados/responsavel/editar/",
        views.editar_responsavel_view,
        name="editar_responsavel",
    ),
    path("usuarios/", views.usuarios_view, name="usuarios"),
    path(
        "usuarios/aventureiro/<int:pk>/ativo/",
        views.aventureiro_toggle_ativo_view,
        name="aventureiro_toggle_ativo",
    ),
    path(
        "usuarios/aventureiro/<int:pk>/termos/",
        views.aventureiro_termos_view,
        name="aventureiro_termos",
    ),
    path(
        "usuarios/conta/<int:conta_id>/principal/",
        views.usuario_principal_view,
        name="usuario_principal",
    ),
    path("eventos/", views.eventos_view, name="eventos"),
    path("eventos/novo/", views.evento_novo_view, name="evento_novo"),
    path("eventos/complexo/novo/", views.evento_complexo_novo_view, name="evento_complexo_novo"),
    path("eventos/<int:pk>/excluir/", views.evento_excluir_view, name="evento_excluir"),
    path("eventos/<int:pk>/", views.evento_painel_view, name="evento_painel"),
    path("eventos/<int:pk>/pagina/", views.evento_pagina_view, name="evento_pagina"),
    path("eventos/<int:pk>/inscrever/", views.evento_inscrever_view, name="evento_inscrever"),
    path(
        "eventos/<int:pk>/inscrever/sucesso/",
        views.evento_inscricao_sucesso_view,
        name="evento_inscricao_sucesso",
    ),
    path(
        "eventos/<int:pk>/inscricoes/<int:inscricao_id>/cancelar/",
        views.evento_inscricao_cancelar_view,
        name="evento_inscricao_cancelar",
    ),
    path(
        "eventos/<int:pk>/produtos/novo/",
        views.evento_produto_novo_view,
        name="evento_produto_novo",
    ),
    path(
        "eventos/<int:pk>/produtos/<int:produto_id>/editar/",
        views.evento_produto_editar_view,
        name="evento_produto_editar",
    ),
    path(
        "eventos/<int:pk>/produtos/<int:produto_id>/excluir/",
        views.evento_produto_excluir_view,
        name="evento_produto_excluir",
    ),
    path("eventos/<int:pk>/loja/", views.evento_loja_view, name="evento_loja"),
    path("eventos/<int:pk>/loja/pagamento/", views.evento_pagamento_view, name="evento_pagamento"),
    path("eventos/<int:pk>/pdv/", views.evento_pdv_view, name="evento_pdv"),
    path("eventos/<int:pk>/pdv/inscricao/", views.evento_pdv_inscricao_view, name="evento_pdv_inscricao"),
    path("eventos/<int:pk>/operar/", views.evento_operar_view, name="evento_operar"),
    path("eventos/<int:pk>/dia/", views.evento_dia_view, name="evento_dia"),
    path("eventos/<int:pk>/dia/checkin/", views.evento_checkin_view, name="evento_checkin"),
    path("eventos/<int:pk>/dia/entrega/", views.evento_entrega_view, name="evento_entrega"),
    path("eventos/<int:pk>/operadores/", views.evento_operadores_view, name="evento_operadores"),
    path("eventos/<int:pk>/operadores/diretoria/", views.evento_operador_add_diretoria_view, name="evento_operador_add_diretoria"),
    path("eventos/<int:pk>/operadores/externo/", views.evento_operador_add_externo_view, name="evento_operador_add_externo"),
    path("eventos/<int:pk>/operadores/<int:operador_id>/reset/", views.evento_operador_reset_view, name="evento_operador_reset"),
    path("eventos/<int:pk>/operadores/<int:operador_id>/remover/", views.evento_operador_remover_view, name="evento_operador_remover"),
    path(
        "eventos/<int:pk>/loja/sucesso/",
        views.evento_pedido_sucesso_view,
        name="evento_pedido_sucesso",
    ),
    path(
        "eventos/<int:pk>/pedidos/<int:pedido_id>/cancelar/",
        views.evento_pedido_cancelar_view,
        name="evento_pedido_cancelar",
    ),
    path("eventos/<int:pk>/custos/novo/", views.evento_custo_novo_view, name="evento_custo_novo"),
    path(
        "eventos/<int:pk>/custos/<int:custo_id>/excluir/",
        views.evento_custo_excluir_view,
        name="evento_custo_excluir",
    ),
    path("eventos/<int:pk>/descontos/novo/", views.evento_cupom_novo_view, name="evento_cupom_novo"),
    path(
        "eventos/<int:pk>/descontos/<int:cupom_id>/excluir/",
        views.evento_cupom_excluir_view,
        name="evento_cupom_excluir",
    ),
    path(
        "eventos/<int:pk>/cupom/validar/",
        views.evento_cupom_validar_view,
        name="evento_cupom_validar",
    ),
    path(
        "eventos/<int:pk>/inscricoes/config/",
        views.evento_inscricao_config_view,
        name="evento_inscricao_config",
    ),
    path(
        "eventos/<int:pk>/inscricoes/faixa/novo/",
        views.evento_faixa_nova_view,
        name="evento_faixa_nova",
    ),
    path(
        "eventos/<int:pk>/inscricoes/faixa/<int:faixa_id>/excluir/",
        views.evento_faixa_excluir_view,
        name="evento_faixa_excluir",
    ),
    path(
        "eventos/<int:pk>/inscricoes/campo/novo/",
        views.evento_campo_novo_view,
        name="evento_campo_novo",
    ),
    path(
        "eventos/<int:pk>/inscricoes/campo/<int:campo_id>/excluir/",
        views.evento_campo_excluir_view,
        name="evento_campo_excluir",
    ),
    path(
        "eventos/<int:pk>/inscricoes/campo/<int:campo_id>/mover/",
        views.evento_campo_mover_view,
        name="evento_campo_mover",
    ),
    path("whatsapp/", views.whatsapp_view, name="whatsapp"),
    path("whatsapp/config/", views.whatsapp_config_view, name="whatsapp_config"),
    path("whatsapp/enviar/", views.whatsapp_enviar_view, name="whatsapp_enviar"),
    # --- Configurações IA (API do GPT / OpenAI) ---
    path("ia/", views.ia_view, name="ia"),
    path("ia/config/", views.ia_config_view, name="ia_config"),
    path("ia/testar/", views.ia_testar_view, name="ia_testar"),
    path("ia/zerar/", views.ia_zerar_view, name="ia_zerar"),
    # --- Pagamentos (Mercado Pago) ---
    path("mercadopago/", views.mercadopago_view, name="mercadopago"),
    path("mercadopago/config/", views.mercadopago_config_view, name="mercadopago_config"),
    path("webhooks/mercadopago/", views.mercadopago_webhook, name="mercadopago_webhook"),
    path("pagamento/<str:ref>/status/", views.pagamento_status_view, name="pagamento_status"),
    path("pagamento/<str:ref>/simular/", views.pagamento_simular_view, name="pagamento_simular"),
    path("pagamento/<str:ref>/sucesso/", views.pagamento_sucesso_view, name="pagamento_sucesso"),
    path("pagamento/<str:ref>/", views.pagamento_view, name="pagamento"),
    # --- Acerto de mensalidades (link público do WhatsApp de cobrança) ---
    path("acerto/<str:token>/", views.acerto_view, name="acerto"),
    path("acerto/<str:token>/cobrar/", views.acerto_cobrar_view, name="acerto_cobrar"),
    path("trocar-perfil/", views.trocar_perfil_view, name="trocar_perfil"),
    path("presenca/", views.presenca_view, name="presenca"),
    path("presenca/<int:pk>/", views.presenca_evento_view, name="presenca_evento"),
    path("presenca/<int:pk>/marcar/", views.presenca_marcar_view, name="presenca_marcar"),
    path("cadastro/", views.cadastro_view, name="cadastro"),
    path(
        "cadastro/aventureiro/",
        views.cadastro_aventureiro_view,
        name="cadastro_aventureiro",
    ),
    path(
        "cadastro/diretoria/",
        views.cadastro_diretoria_view,
        name="cadastro_diretoria",
    ),
    path(
        "cadastro/novo-aventureiro/",
        views.cadastro_novo_aventureiro_view,
        name="cadastro_novo_aventureiro",
    ),
    path("cadastro/sucesso/", views.cadastro_sucesso_view, name="cadastro_sucesso"),
    path("usuarios/diretoria/", views.diretoria_equipe_view, name="diretoria_equipe"),
    path(
        "usuarios/diretoria/<int:pk>/papel/",
        views.diretoria_papel_view,
        name="diretoria_papel",
    ),
    path("trocar-senha/", views.trocar_senha_view, name="trocar_senha"),
    path("recuperar-senha/", views.recuperar_senha_view, name="recuperar_senha"),
    path(
        "recuperar-senha/codigo/",
        views.recuperar_senha_codigo_view,
        name="recuperar_senha_codigo",
    ),
    path(
        "recuperar-senha/reenviar/",
        views.recuperar_senha_reenviar_view,
        name="recuperar_senha_reenviar",
    ),
    path(
        "recuperar-senha/nova-senha/",
        views.recuperar_senha_nova_view,
        name="recuperar_senha_nova",
    ),
    # --- Loja do Clube (loja oficial) ---
    path("loja/", views.loja_view, name="loja"),
    path("loja/produto/novo/", views.loja_produto_novo_view, name="loja_produto_novo"),
    path("loja/produto/<int:pk>/editar/", views.loja_produto_editar_view, name="loja_produto_editar"),
    path("loja/produto/<int:pk>/excluir/", views.loja_produto_excluir_view, name="loja_produto_excluir"),
    path("loja/produto/<int:pk>/", views.loja_produto_view, name="loja_produto"),
    path("loja/carrinho/adicionar/", views.loja_carrinho_add_view, name="loja_carrinho_add"),
    path("loja/carrinho/remover/", views.loja_carrinho_remover_view, name="loja_carrinho_remover"),
    path("loja/finalizar/", views.loja_finalizar_view, name="loja_finalizar"),
    path("loja/pagamento/", views.loja_pagamento_view, name="loja_pagamento"),
    path("loja/sucesso/", views.loja_sucesso_view, name="loja_sucesso"),
    path("loja/compra/<int:compra_id>/cancelar/", views.loja_compra_cancelar_view, name="loja_compra_cancelar"),
    path("loja/entrega/", views.loja_entrega_view, name="loja_entrega"),
    path("loja/entrega/compra/", views.loja_entrega_compra_view, name="loja_entrega_compra"),
    # --- Mensalidades ---
    path("mensalidades/", views.mensalidades_view, name="mensalidades"),
    path("mensalidades/config/", views.mensalidade_config_view, name="mensalidade_config"),
    path("mensalidades/reajustar/", views.mensalidade_reajustar_view, name="mensalidade_reajustar"),
    path("mensalidades/gerar/", views.mensalidades_gerar_view, name="mensalidades_gerar"),
    path("mensalidades/pagar/", views.mensalidade_pagar_view, name="mensalidade_pagar"),
    path("mensalidades/cobrar/", views.mensalidade_cobrar_view, name="mensalidade_cobrar"),
    path("mensalidades/pagar-selecionadas/", views.minhas_mensalidades_pagar_view, name="minhas_mensalidades_pagar"),
    path("mensalidades/cobrancas/config/", views.mensalidade_cobranca_config_view, name="mensalidade_cobranca_config"),
    path("mensalidades/cobrancas/modo/", views.mensalidade_cobranca_modo_view, name="mensalidade_cobranca_modo"),
    path("mensalidades/cobrancas/telefone/", views.mensalidade_cobranca_telefone_view, name="mensalidade_cobranca_telefone"),
    path("mensalidades/cobrancas/enviar/", views.mensalidade_cobranca_enviar_view, name="mensalidade_cobranca_enviar"),
    path("mensalidades/isencao/", views.mensalidade_isencao_view, name="mensalidade_isencao"),
    path("mensalidades/editar/", views.mensalidade_editar_view, name="mensalidade_editar"),
    # --- Financeiro geral ---
    path("financeiro/", views.financeiro_view, name="financeiro"),
    path("financeiro/custo/novo/", views.custo_clube_novo_view, name="custo_clube_novo"),
    path("financeiro/custo/<int:custo_id>/excluir/", views.custo_clube_excluir_view, name="custo_clube_excluir"),
    path("financeiro/caixa/", views.caixa_editar_view, name="caixa_editar"),
]
