# Generated by Django 5.2.16 on 2026-09-13 22:55

import django.db.models.deletion
import leilao.models
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PagamentoLeilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('referencia', models.CharField(max_length=60, unique=True, verbose_name='Referência')),
                ('mp_payment_id', models.CharField(blank=True, db_index=True, max_length=40, verbose_name='ID no Mercado Pago')),
                ('status', models.CharField(choices=[('pendente', 'Pendente'), ('aprovado', 'Aprovado'), ('rejeitado', 'Rejeitado'), ('cancelado', 'Cancelado'), ('estornado', 'Estornado')], default='pendente', max_length=12, verbose_name='Situação')),
                ('valor_bruto', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor (R$)')),
                ('taxa', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Taxa (R$)')),
                ('valor_liquido', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Líquido (R$)')),
                ('qr_code', models.TextField(blank=True, verbose_name='Pix copia e cola')),
                ('qr_code_base64', models.TextField(blank=True, verbose_name='QR (imagem base64)')),
                ('ticket_url', models.URLField(blank=True, max_length=500, verbose_name='Link do Mercado Pago')),
                ('payload', models.TextField(blank=True, verbose_name='Retorno bruto (JSON)')),
                ('finalizado', models.BooleanField(default=False, help_text='Trava de idempotência: o webhook do MP repete o aviso.', verbose_name='Já processado')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Pagamento do leilão',
                'verbose_name_plural': 'Pagamentos do leilão',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Participante',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=150, verbose_name='Nome completo')),
                ('whatsapp', models.CharField(max_length=20, verbose_name='WhatsApp')),
                ('cep', models.CharField(blank=True, max_length=9, verbose_name='CEP')),
                ('logradouro', models.CharField(blank=True, max_length=150, verbose_name='Rua / Avenida')),
                ('numero', models.CharField(blank=True, max_length=20, verbose_name='Número')),
                ('complemento', models.CharField(blank=True, max_length=60, verbose_name='Complemento')),
                ('bairro', models.CharField(blank=True, max_length=80, verbose_name='Bairro')),
                ('cidade', models.CharField(blank=True, max_length=80, verbose_name='Cidade')),
                ('estado', models.CharField(blank=True, max_length=2, verbose_name='UF')),
                ('token', models.CharField(default=leilao.models._novo_token, editable=False, max_length=64, unique=True, verbose_name='Token')),
                ('bloqueado', models.BooleanField(default=False, help_text='Bloqueia novos lances (ex.: arrematou e não pagou).', verbose_name='Bloqueado')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação do locutor')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Entrou em')),
                ('ultimo_visto_em', models.DateTimeField(blank=True, null=True, verbose_name='Visto por último')),
            ],
            options={
                'verbose_name': 'Participante',
                'verbose_name_plural': 'Participantes',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ConfigLeilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('modo', models.CharField(choices=[('teste', 'Teste (sandbox)'), ('producao', 'Produção')], default='teste', max_length=10, verbose_name='Modo')),
                ('access_token_teste', models.CharField(blank=True, max_length=255, verbose_name='Access Token de teste')),
                ('webhook_secret_teste', models.CharField(blank=True, max_length=255, verbose_name='Assinatura secreta do webhook (teste)')),
                ('access_token_prod', models.CharField(blank=True, max_length=255, verbose_name='Access Token de produção')),
                ('webhook_secret_prod', models.CharField(blank=True, max_length=255, verbose_name='Assinatura secreta do webhook (produção)')),
                ('site_url', models.URLField(blank=True, help_text='Ex.: https://pinhaljunior.com.br/leilao — usado no webhook do Mercado Pago.', verbose_name='Endereço público do leilão')),
                ('audio_ativo', models.BooleanField(default=False, verbose_name='Transmitir a voz do locutor')),
                ('audio_caminho', models.CharField(default='leilao', help_text="Nome do 'path' configurado no MediaMTX (ex.: leilao).", max_length=60, verbose_name='Caminho no MediaMTX')),
                ('audio_publicar_usuario', models.CharField(blank=True, max_length=60, verbose_name='Usuário de publicação')),
                ('audio_publicar_senha', models.CharField(blank=True, max_length=120, verbose_name='Senha de publicação')),
                ('audio_externo_url', models.URLField(blank=True, help_text='Preenchido só se o áudio próprio for descartado. A tela passa a apontar para cá.', verbose_name='Plano B: link de live externa')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
                ('atualizado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Atualizado por')),
            ],
            options={
                'verbose_name': 'Configuração do leilão',
                'verbose_name_plural': 'Configuração do leilão',
            },
        ),
        migrations.CreateModel(
            name='Leilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=120, verbose_name='Nome do leilão')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('status', models.CharField(choices=[('rascunho', 'Rascunho'), ('ao_vivo', 'Ao vivo'), ('encerrado', 'Encerrado')], default='rascunho', max_length=12, verbose_name='Situação')),
                ('incremento_padrao', models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='Quanto cada toque no botão soma. Padrão: R$ 5,00.', max_digits=10, verbose_name='Incremento do lance (R$)')),
                ('segundos_por_lote', models.PositiveIntegerField(default=60, help_text='Contagem regressiva de cada lote. Padrão: 60 s.', verbose_name='Cronômetro do lote (segundos)')),
                ('reiniciar_cronometro', models.BooleanField(default=True, help_text="Regra clássica anti-'lance no último segundo'.", verbose_name='Reiniciar o cronômetro a cada lance')),
                ('segundos_extra', models.PositiveIntegerField(default=30, help_text="Quanto o botão '+tempo' do locutor acrescenta.", verbose_name='Botão de tempo extra (segundos)')),
                ('minutos_para_pagar', models.PositiveIntegerField(default=15, help_text='Passou disso sem pagar, o lote volta para a fila.', verbose_name='Prazo para pagar (minutos)')),
                ('chat_segundos', models.PositiveIntegerField(default=120, help_text='Quanto tempo o chat fica aberto no intervalo. 0 = não abre sozinho.', verbose_name='Duração do chat entre lotes (segundos)')),
                ('chat_aberto_ate', models.DateTimeField(blank=True, null=True, verbose_name='Chat aberto até')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='leiloes_criados', to=settings.AUTH_USER_MODEL, verbose_name='Criado por')),
            ],
            options={
                'verbose_name': 'Leilão',
                'verbose_name_plural': 'Leilões',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Lote',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ordem', models.PositiveIntegerField(default=0, verbose_name='Ordem na fila')),
                ('nome', models.CharField(max_length=120, verbose_name='Item')),
                ('descricao', models.CharField(blank=True, help_text='Uma linha: é o que cabe na tela do celular embaixo da foto.', max_length=240, verbose_name='Descrição curta')),
                ('foto', models.ImageField(blank=True, upload_to='lotes/', verbose_name='Foto')),
                ('foto_mini', models.ImageField(blank=True, upload_to='lotes/mini/', verbose_name='Miniatura')),
                ('lance_inicial', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Lance inicial (R$)')),
                ('incremento', models.DecimalField(blank=True, decimal_places=2, help_text='Vazio = usa o incremento do leilão.', max_digits=10, null=True, verbose_name='Incremento próprio (R$)')),
                ('status', models.CharField(choices=[('fila', 'Na fila'), ('aberto', 'Em pregão'), ('vendido', 'Vendido'), ('sem_lance', 'Sem lance'), ('cancelado', 'Cancelado')], default='fila', max_length=12, verbose_name='Situação')),
                ('valor_atual', models.DecimalField(decimal_places=2, default=Decimal('0.00'), max_digits=10, verbose_name='Valor atual (R$)')),
                ('aberto_em', models.DateTimeField(blank=True, null=True, verbose_name='Aberto em')),
                ('fecha_em', models.DateTimeField(blank=True, help_text='Data/hora ABSOLUTA do fim do cronômetro. O cliente só desenha a diferença.', null=True, verbose_name='Fecha em')),
                ('pausado_restante', models.PositiveIntegerField(blank=True, help_text='Preenchido só enquanto o locutor pausa o cronômetro.', null=True, verbose_name='Segundos restantes (pausado)')),
                ('fechado_em', models.DateTimeField(blank=True, null=True, verbose_name='Fechado em')),
                ('voltas', models.PositiveIntegerField(default=0, help_text='Quantas vezes voltou por falta de pagamento.', verbose_name='Voltas para a fila')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lotes', to='leilao.leilao')),
                ('lider', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lotes_liderando', to='leilao.participante', verbose_name='Quem está ganhando')),
            ],
            options={
                'verbose_name': 'Lote',
                'verbose_name_plural': 'Lotes',
                'ordering': ['ordem', 'id'],
            },
        ),
        migrations.CreateModel(
            name='MensagemChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300, verbose_name='Mensagem')),
                ('removida', models.BooleanField(default=False, verbose_name='Removida')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Em')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='leilao.leilao')),
                ('participante', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='mensagens', to='leilao.participante')),
            ],
            options={
                'verbose_name': 'Mensagem do chat',
                'verbose_name_plural': 'Mensagens do chat',
                'ordering': ['criado_em', 'id'],
                'indexes': [models.Index(fields=['leilao', 'criado_em'], name='leilao_mens_leilao__c846ed_idx')],
            },
        ),
        migrations.CreateModel(
            name='Lance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('origem', models.CharField(choices=[('botao', 'Botão do participante'), ('locutor', 'Registrado pelo locutor')], default='botao', max_length=10, verbose_name='Origem')),
                ('cancelado', models.BooleanField(default=False, verbose_name='Desfeito')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Em')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='leilao.lote')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lances', to='leilao.participante')),
            ],
            options={
                'verbose_name': 'Lance',
                'verbose_name_plural': 'Lances',
                'ordering': ['-criado_em', '-id'],
                'indexes': [models.Index(fields=['lote', '-criado_em'], name='leilao_lanc_lote_id_236f38_idx')],
            },
        ),
        migrations.CreateModel(
            name='Arremate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Valor (R$)')),
                ('status', models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('pago', 'Pago'), ('expirado', 'Não pago (venceu o prazo)'), ('cancelado', 'Cancelado')], default='aguardando', max_length=12, verbose_name='Situação')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Arrematado em')),
                ('expira_em', models.DateTimeField(verbose_name='Prazo para pagar')),
                ('pago_em', models.DateTimeField(blank=True, null=True, verbose_name='Pago em')),
                ('pago_manual', models.BooleanField(default=False, help_text='Marcado pelo locutor (pagou em dinheiro, transferência, etc.).', verbose_name='Baixa manual')),
                ('observacao', models.CharField(blank=True, max_length=200, verbose_name='Observação')),
                ('lote', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arremates', to='leilao.lote')),
                ('pagamento', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='arremates', to='leilao.pagamentoleilao', verbose_name='Cobrança Pix')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='arremates', to='leilao.participante')),
            ],
            options={
                'verbose_name': 'Arremate',
                'verbose_name_plural': 'Arremates',
                'ordering': ['-criado_em'],
                'indexes': [models.Index(fields=['participante', '-criado_em'], name='leilao_arre_partici_487abf_idx')],
            },
        ),
    ]
