# Generated by Django 5.2.16 on 2026-09-14 00:27

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arremate',
            name='entrega_obs',
            field=models.CharField(blank=True, help_text='Quem recebeu, código de rastreio, combinado de retirada…', max_length=200, verbose_name='Observação da entrega'),
        ),
        migrations.AddField(
            model_name='arremate',
            name='entregue_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Entregue em'),
        ),
        migrations.AddField(
            model_name='arremate',
            name='entregue_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='entregas_leilao', to=settings.AUTH_USER_MODEL, verbose_name='Entregue por'),
        ),
        migrations.AlterField(
            model_name='arremate',
            name='pago_manual',
            field=models.BooleanField(default=False, help_text='Marcado pelo caixa (pagou em dinheiro, transferência, etc.).', verbose_name='Baixa manual'),
        ),
    ]
