# Generated by Django 5.2.16 on 2026-09-14 01:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0002_arremate_entrega_obs_arremate_entregue_em_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='configleilao',
            name='musica',
            field=models.FileField(blank=True, help_text='MP3/OGG que o clube tenha direito de usar. Sem arquivo, a tela toca uma base ambiente gerada no próprio navegador.', upload_to='musica/', verbose_name='Música de fundo (opcional)'),
        ),
        migrations.AddField(
            model_name='leilao',
            name='fechamento_automatico',
            field=models.BooleanField(default=False, help_text="Desligado (padrão): o cronômetro chega a zero e ESPERA — quem bate o martelo é o locutor, pelo botão VENDIDO. É assim que um leilão de verdade funciona: o 'dou-lhe uma, dou-lhe duas' é do leiloeiro.", verbose_name='Fechar o lote sozinho quando o tempo acabar'),
        ),
        migrations.AddField(
            model_name='leilao',
            name='musica_ligada',
            field=models.BooleanField(default=False, verbose_name='Música de fundo tocando'),
        ),
        migrations.AddField(
            model_name='leilao',
            name='musica_volume',
            field=models.PositiveSmallIntegerField(default=18, help_text='Baixinho de propósito: é fundo, não show. O locutor ajusta ao vivo.', verbose_name='Volume da música (%)'),
        ),
    ]
