# Generated by Django 5.2.16 on 2026-09-14 01:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0003_configleilao_musica_leilao_fechamento_automatico_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='chat_aberto_em',
            field=models.DateTimeField(blank=True, help_text='Marco da rodada atual do chat. Cada intervalo é uma conversa NOVA para quem participa — abre limpa. O locutor continua vendo tudo.', null=True, verbose_name='Chat aberto em'),
        ),
    ]
