# Generated by Django 5.2.16 on 2026-09-14 01:47

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0004_leilao_chat_aberto_em'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arremate',
            name='combinado_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Combinado em'),
        ),
        migrations.AddField(
            model_name='arremate',
            name='combinado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='acertos_leilao', to=settings.AUTH_USER_MODEL, verbose_name='Quem falou com a pessoa'),
        ),
        migrations.AlterField(
            model_name='arremate',
            name='observacao',
            field=models.CharField(blank=True, help_text='O que foi combinado com a pessoa sobre o pagamento.', max_length=200, verbose_name='Observação'),
        ),
        migrations.AlterField(
            model_name='arremate',
            name='status',
            field=models.CharField(choices=[('aguardando', 'Aguardando pagamento'), ('combinado', 'Combinado — vai pagar depois'), ('pago', 'Pago'), ('expirado', 'Não pago (venceu o prazo)'), ('cancelado', 'Cancelado')], default='aguardando', max_length=12, verbose_name='Situação'),
        ),
    ]
