# Generated by Django 5.2.16 on 2026-09-14 03:00
#
# A numeração interna do item — o número que vai colado no objeto físico.
#
# A ordem das operações importa. O campo `numero` nasce com `default=0`, então
# todos os lotes já cadastrados ficariam com o MESMO número e a constraint de
# unicidade quebraria na hora de ser criada. O `RunPython` no meio é o que
# numera o que já existe antes de a regra passar a valer — e ele também acerta
# o contador do leilão, senão o próximo item cadastrado começaria do 1 e
# colidiria com o que acabou de ser numerado.

from django.db import migrations, models


def numerar_o_que_ja_existe(apps, schema_editor):
    """Dá número aos lotes cadastrados antes deste campo existir.

    Numera por `ordem` (e `id` para desempatar), que é a sequência em que a
    equipe já enxerga a lista — assim o número bate com o que ela esperava.
    """
    Lote = apps.get_model("leilao", "Lote")
    Leilao = apps.get_model("leilao", "Leilao")
    for leilao in Leilao.objects.all():
        n = 0
        for n, lote in enumerate(
            Lote.objects.filter(leilao=leilao).order_by("ordem", "id"), start=1
        ):
            lote.numero = n
            lote.save(update_fields=["numero"])
        # O contador precisa continuar de onde a numeração parou.
        leilao.ultimo_numero_item = n
        leilao.save(update_fields=["ultimo_numero_item"])


def desfazer(apps, schema_editor):
    """Nada a fazer: os campos somem na volta."""


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0005_arremate_combinado_em_arremate_combinado_por_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='ultimo_numero_item',
            field=models.PositiveIntegerField(default=0, verbose_name='Último nº de item usado'),
        ),
        migrations.AddField(
            model_name='lote',
            name='numero',
            field=models.PositiveIntegerField(default=0, editable=False, verbose_name='Nº do item'),
        ),
        migrations.RunPython(numerar_o_que_ja_existe, desfazer),
        migrations.AddConstraint(
            model_name='lote',
            constraint=models.UniqueConstraint(fields=('leilao', 'numero'), name='numero_unico_por_leilao'),
        ),
    ]
