# Generated by Django 5.2.16 on 2026-09-15 23:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0006_leilao_ultimo_numero_item_lote_numero_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='ContaEquipe',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(blank=True, help_text='Como o diretor escreveu no cadastro — é o que a equipe lê na lista.', max_length=150, verbose_name='Nome da pessoa')),
                ('senha_provisoria', models.BooleanField(default=True, help_text='Enquanto verdadeiro, a pessoa só abre a tela de trocar a senha.', verbose_name='Ainda com a senha padrão')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criada em')),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='contas_leilao_criadas', to=settings.AUTH_USER_MODEL, verbose_name='Criada por')),
                ('usuario', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='conta_leilao', to=settings.AUTH_USER_MODEL, verbose_name='Conta')),
            ],
            options={
                'verbose_name': 'Conta da equipe',
                'verbose_name_plural': 'Contas da equipe',
                'ordering': ['nome'],
            },
        ),
    ]
