# Generated by Django 5.2.16 on 2026-09-16 01:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0007_contaequipe'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='boas_vindas_texto',
            field=models.TextField(blank=True, default='O leilão começa em instantes — pode deixar esta tela aberta.\nCada toque no botão soma R$ 5 ao lance.\nQuem arremata paga por Pix na hora, sem sair da tela.\nLigue o som para ouvir o locutor ao vivo.', help_text='Uma informação por linha. Dá para editar com o leilão já no ar.', verbose_name='Informações úteis'),
        ),
        migrations.AddField(
            model_name='leilao',
            name='boas_vindas_titulo',
            field=models.CharField(default='Seja bem-vindo!', help_text='Aparece grande para quem entra antes do primeiro item.', max_length=80, verbose_name='Título da tela de espera'),
        ),
    ]
