# Generated by Django 5.2.16 on 2026-09-17 23:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0008_leilao_boas_vindas_texto_leilao_boas_vindas_titulo'),
    ]

    operations = [
        migrations.CreateModel(
            name='AtribuicaoEntrega',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entregador', models.PositiveSmallIntegerField(default=0, verbose_name='Entregador')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Movida em')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_entrega', to='leilao.leilao', verbose_name='Leilão')),
                ('participante', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='atribuicoes_entrega', to='leilao.participante', verbose_name='Quem recebe')),
            ],
            options={
                'verbose_name': 'Parada do quadro de entregas',
                'verbose_name_plural': 'Paradas do quadro de entregas',
                'unique_together': {('leilao', 'participante')},
            },
        ),
        migrations.CreateModel(
            name='EntregadorLeilao',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveSmallIntegerField(verbose_name='Entregador')),
                ('nome', models.CharField(blank=True, max_length=80, verbose_name='Nome')),
                ('leilao', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='entregadores', to='leilao.leilao', verbose_name='Leilão')),
            ],
            options={
                'verbose_name': 'Entregador',
                'verbose_name_plural': 'Entregadores',
                'ordering': ['numero'],
                'unique_together': {('leilao', 'numero')},
            },
        ),
    ]
