# Generated by Django 5.2.16 on 2026-09-19 17:25

import django.core.validators
from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0009_atribuicaoentrega_entregadorleilao'),
    ]

    operations = [
        migrations.AddField(
            model_name='lote',
            name='altura_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Altura (cm)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='largura_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Largura (cm)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='peso_kg',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Aproximado, em quilos. Pode usar vírgula (ex.: 1,5).', max_digits=7, null=True, validators=[django.core.validators.MinValueValidator(Decimal('0.01')), django.core.validators.MaxValueValidator(Decimal('1000'))], verbose_name='Peso (kg)'),
        ),
        migrations.AddField(
            model_name='lote',
            name='profundidade_cm',
            field=models.PositiveIntegerField(blank=True, null=True, validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(1000)], verbose_name='Profundidade (cm)'),
        ),
    ]
