# Generated by Django 5.2.16 on 2026-09-22 01:30

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0010_peso_e_dimensoes_do_lote'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='pagamentos_liberados',
            field=models.BooleanField(default=False, help_text='Ligado pelo locutor no fim do leilão, libera todo mundo a pagar.', verbose_name='Pagamentos liberados'),
        ),
        migrations.AlterField(
            model_name='arremate',
            name='expira_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Prazo para pagar'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='chat_segundos',
            field=models.PositiveIntegerField(default=120, help_text='DORMENTE — o chat fica aberto o leilão inteiro.', verbose_name='Duração do chat entre lotes (segundos)'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='incremento_padrao',
            field=models.DecimalField(decimal_places=2, default=Decimal('5.00'), help_text='DORMENTE — o incremento é fixo em R$ 5,00.', max_digits=10, verbose_name='Incremento do lance (R$)'),
        ),
        migrations.AlterField(
            model_name='leilao',
            name='minutos_para_pagar',
            field=models.PositiveIntegerField(default=15, help_text='DORMENTE — não há prazo; o pagamento é liberado no fim.', verbose_name='Prazo para pagar (minutos)'),
        ),
        migrations.AlterField(
            model_name='lote',
            name='incremento',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='DORMENTE — o incremento é fixo em R$ 5,00.', max_digits=10, null=True, verbose_name='Incremento próprio (R$)'),
        ),
    ]
