# Generated by Django 5.2.16 on 2026-09-23 11:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0011_pagamento_no_fim_e_incremento_fixo'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='arremate',
            name='devolvido_em',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Devolvido ao leilão em'),
        ),
        migrations.AddField(
            model_name='arremate',
            name='devolvido_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='devolucoes_leilao', to=settings.AUTH_USER_MODEL, verbose_name='Quem devolveu'),
        ),
        migrations.AddField(
            model_name='arremate',
            name='motivo_devolucao',
            field=models.CharField(blank=True, help_text='Aparece no histórico do item e na tela do caixa.', max_length=200, verbose_name='Por que voltou ao leilão'),
        ),
    ]
