# Generated by Django 5.2.16 on 2026-09-24 00:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0012_devolver_item_ao_leilao'),
    ]

    operations = [
        migrations.AddField(
            model_name='leilao',
            name='som_arremate',
            field=models.BooleanField(default=True, help_text='Toca na tela de todo mundo quando o martelo bate.', verbose_name='Som de arremate (palmas)'),
        ),
        migrations.AddField(
            model_name='leilao',
            name='som_lance',
            field=models.BooleanField(default=True, help_text='Toca na tela de todo mundo a cada lance.', verbose_name='Som de lance (caixa registradora)'),
        ),
    ]
