# Generated by Django 5.2.17 on 2026-09-24 18:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leilao', '0013_som_da_sala'),
    ]

    operations = [
        migrations.AddField(
            model_name='pagamentoleilao',
            name='cobre',
            field=models.JSONField(blank=True, default=list, verbose_name='Arremates cobertos'),
        ),
    ]
